[build]
  command = "java -version && pwd && ls -l gradlew && chmod +x gradlew && ./gradlew clean assembleDebug --no-daemon --stacktrace"
  publish = "app/build/outputs/apk/debug/"

[build.environment]
  JAVA_VERSION = "17"
  ANDROID_HOME = "/opt/android/sdk"
  GRADLE_OPTS = "-Xmx2048m -Dorg.gradle.daemon=false"